name: Build for macOS

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    permissions:
      contents: write
    runs-on: macos-latest
    env:
      NAME_APP: translator

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./target"

      - name: Build app
        run: |
          cargo build --release

      - name: Package binary
        run: |
          mkdir -p dist
          cd target/release
          tar -czf ../../../dist/translator-${GITHUB_REF_NAME#v}-macos-x86_64.tar.gz translator
          ls -la ../../../dist/

      - name: Upload to Existing Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/translator-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
